### PR TITLE
fix name to make "npm shrinkwrap" work

### PR DESCRIPTION
**Pull request by fjakobs**

### CODE REVIEW

**Comment by tomgco** [comment]
Awesome, Thanks!

**Comment by tomgco** [comment]
Will publish this as soon as I can.

**Comment by fjakobs** [comment]
Awesome. Would be cool to have it on NPM soon.

**Comment by tomgco** [comment]
`1.0.3` is now up on npm.

**Comment by fjakobs** [comment]
excellent

**Pull request merged**
